version: "3.8"

services:
  app:
    container_name: slate-reusable-component
    image: slate-reusable-component
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
      - 3001:3001