export const tableScreensColumnStructure = [
  {
    table_id: 2,
    col_name: 'expand',
    col_visible: true,
    col_label: '>',
    col_type: 'symbol',
    col_value: ['fnExpand', '0'],
    col_subValue: null,
    col_link: null,
    col_width: 3,
    col_minWidth: 10,
    col_sort: null,
  },
  {
    table_id: 2,
    col_name: 'screen',
    col_visible: true,
    col_label: 'Screen Name',
    col_type: 'string',
    col_value: ['fnNameValueLink', 'screen'],
    col_subValue: ['fnLabelStringValues', 'Code: ', 'screenCode'],
    col_link: ['page', 'screenId'],
    col_width: 20,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    table_id: 2,
    col_name: 'scheduleStatus',
    col_visible: true,
    col_label: 'Schedule\nStatus',
    col_type: 'string',
    col_value: ['scheduleStatus'],
    col_subValue: ['fnDateValues', 'dmy24', 'takenOn'],
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'playLogStatus',
    col_visible: true,
    col_label: 'Playlog\nStatus',
    col_type: 'string',
    col_value: ['playLogStatus'],
    col_subValue: ['fnDateValues', 'dmy24', 'lastPlayedOn'],
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'spotsMaximum',
    col_visible: true,
    col_label: 'Spots\nMaximum',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsMaximum'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsScheduled'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'spotsPossible',
    col_visible: true,
    col_label: 'Spots\nMovies',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsPossible'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'string',
    col_value: ['spotsPlayed'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 2,
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'number',
    col_value: ['fnNumValues', 'fp', 'spotsPlayedPercent'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
];

export const tableScreensSubRowStructure = [
  {
    row_num: 1,
    row_name: 'composition',
    row_type: 'string',
    row_flex: '3.0',
    row_value: ['fnLabelStringValues', '', 'composition'],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'theatre',
    row_type: 'string',
    row_flex: '3.0',
    row_value: ['fnLabelStringValues', 'Theatre: ', 'theatre', 'city', 'state'],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'LastCalledOn',
    row_type: 'string',
    row_flex: '3.0',
    row_value: ['fnStringDateValues', 'dmy24', ' ', 'Last Called On: ', 'LastCalledOn'],
    row_link: null,
  },
  {
    row_num: 2,
    row_name: 'shows',
    row_type: 'string',
    row_flex: '1.5',
    row_value: ['fnLabelStringValues', 'Shows: ', 'shows'],
    row_link: null,
  },
  {
    row_num: 2,
    row_name: 'days',
    row_type: 'string',
    row_flex: '1.5',
    row_value: ['fnLabelStringValues', 'Days: ', 'days'],
    row_link: null,
  },
  {
    row_num: 2,
    row_name: 'position',
    row_type: 'string',
    row_flex: '2',
    row_value: ['fnLabelStringValues', 'Position', 'position', 'prefPosition'],
    row_link: null,
  },
  {
    row_num: 2,
    row_name: 'spotRepetition',
    row_type: 'string',
    row_flex: '1',
    row_value: ['fnLabelStringValues', 'Repetition: ', 'spotRepetition'],
    row_link: null,
  },
  {
    row_num: 2,
    row_name: 'remarks',
    row_type: 'string',
    row_flex: '3',
    row_value: ['fnLabelStringValues', 'Remarks: ', 'remarks'],
    row_link: null,
  },
];
