export const tableOrderColumnStructure = [
  {
    table_id: 0,
    col_name: 'expand',
    col_visible: true,
    col_label: '>',
    col_type: 'symbol',
    col_value: ['fnExpand', '0'], // UKR: default collapsed
    col_subValue: null,
    col_link: null,
    col_width: 3,
    col_minWidth: 10,
    col_sort: null,
  },
  {
    table_id: 0,
    col_name: 'id',
    col_visible: false,
    col_label: 'ID',
    col_type: 'string',
    col_value: null,
    col_subValue: null,
    col_link: null,
    col_width: 0,
    col_minWidth: 5,
    col_sort: null,
  },
  {
    table_id: 0,
    col_name: 'orderId',
    col_visible: true,
    col_label: 'Order ID',
    col_type: 'string',
    col_value: ['fnNameValueLink', 'orderId'], // added logic
    col_subValue: null,
    col_link: ['page', 'orderId'],
    col_width: 15,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    table_id: 0,
    col_name: 'govtRoNo',
    col_visible: true,
    col_label: 'Govt. RO No.',
    col_type: 'string',
    col_value: ['govtRoNo'],
    col_subValue: null,
    col_link: null,
    col_width: 10,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'noOfSchedules',
    col_visible: true,
    col_label: 'Schedule\nCount',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'noOfSchedules'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'spotsMaximum',
    col_visible: true,
    col_label: 'Spots\nMaximum',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsMaximum'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsScheduled'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'spotsPossible',
    col_visible: true,
    col_label: 'Spots\nMovies',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsPossible'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsPlayed'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'takenPercent',
    col_visible: true,
    col_label: 'Taken\nPercent',
    col_type: 'number',
    col_value: ['fnNumValues', 'fp', 'takenPercent'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'playedPercent',
    col_visible: true,
    col_label: 'Played\nPercent',
    col_type: 'number',
    col_value: ['fnNumValues', 'fp', 'playedPercent'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
  {
    table_id: 0,
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'number',
    col_value: ['fnNumValues', 'fp', 'spotsPlayedPercent'],
    col_subValue: null,
    col_link: null,
    col_width: 9,
    col_minWidth: 80,
    col_sort: 'a',
  },
];

export const tableOrderSubRowStructure = [
  {
    row_num: 1,
    row_name: 'client',
    row_type: 'string',
    row_flex: '3',
    row_value: ['fnLabelStringValuesFailuresScreen', 'Client: ', ''],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'noOfScreens',
    row_type: 'string',
    row_flex: '1',
    row_value: ['fnLabelStringValues', 'Screen Count', 'noOfScreens'],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'moviesPlayed',
    row_type: 'string',
    row_flex: '1',
    row_value: ['fnLabelStringValues', 'Movies Played: ', 'moviesPlayed'],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'startDate',
    row_type: 'string',
    row_flex: '1',
    row_value: ['fnStringDateValues', 'dmy', ' - ', 'Min Sch.: ', 'startDate'],
    row_link: null,
  },
  {
    row_num: 1,
    row_name: 'endDate',
    row_type: 'string',
    row_flex: '2',
    row_value: ['fnStringDateValues', 'dmy', ' - ', 'Max Sch.: ', 'endDate'],
    row_link: null,
  },
];

export const summaryCardStructure = [
  {
    className: 'activeIcon',
    response: 'noOfActive',
    label: 'Planned',
  },
  {
    className: 'pausedIcon',
    response: 'noOfProblematic',
    label: 'Logs Pending',
  },
  {
    className: 'consumedIcon',
    response: 'noOfProblematic',
    label: 'Problematic',
  },
  {
    className: 'completedIcon',
    response: 'noOfCompleted',
    label: 'Completed',
  },
  {
    className: 'expiredIcon',
    response: 'noOfUnoptimized',
    label: 'Expired',
  },
  {
    className: 'plannedIcon',
    response: 'noOfPlaned',
    label: 'Planned',
  },
  {
    className: 'draftIcon',
    response: 'problematicPercent',
    label: 'Problematic %',
  },
];
