export const tableShowsColumnStructure = [
  {
    table_id: 3,
    col_name: 'showDate',
    col_visible: true,
    col_label: 'Date',
    col_type: 'string',
    col_value: ['fnDateValues', 'ddmy', 'showDate'],
    col_subValue: null,
    col_link: null,
    col_width: 12,
    col_minWidth: 150,
    col_sort: null,
  },
  {
    table_id: 3,
    col_name: 'startTime',
    col_visible: false,
    col_label: 'Time',
    col_type: 'string',
    col_value: ['fnDateValues', 't24', 'startTime', 'endTime'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'position',
    col_visible: true,
    col_label: 'Position',
    col_type: 'string',
    col_value: ['position'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'prefPosition',
    col_visible: true,
    col_label: 'Pref.\nPosition',
    col_type: 'string',
    col_value: ['prefPosition'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'moviesPlayed',
    col_visible: true,
    col_label: 'Movie\nPlayed',
    col_type: 'string',
    col_value: ['moviesPlayed'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'spotRepetition',
    col_visible: true,
    col_label: 'Repetition',
    col_type: 'string',
    col_value: ['spotRepetition'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'spotsScheduled',
    col_visible: true,
    col_label: 'Spots\nScheduled',
    col_type: 'number',
    col_value: ['fnNumValues', 'i', 'spotsScheduled'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'spotsPlayed',
    col_visible: true,
    col_label: 'Spots\nPlayed',
    col_type: 'string',
    col_value: ['spotsPlayed'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
  {
    table_id: 3,
    col_name: 'spotsPlayedPercent',
    col_visible: true,
    col_label: 'Spots\nPercent',
    col_type: 'string',
    col_value: ['fnNumValues', 'fp', 'spotsPlayedPercent'],
    col_subValue: null,
    col_link: null,
    col_width: 11,
    col_minWidth: 100,
    col_sort: 'a',
  },
];
